# application.yml — común
spring:
  application:
    name: portal-empleo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  jwt:
    issuer: workflow-api
    duracion-token: 1h
    clave-privada: ${JWT_CLAVE_PRIVADA:}
  cors:
    origenes-permitidos: ${CORS_ORIGENES_PERMITIDOS:http://localhost:4200}